FUNCTION COMPUTE_FATIGUE, DATA_SEED, PREV_FLOOR, PREV_FATIGUE
	;theta = 0.5 recall strength
	;mu different foreach floor
	;sigma noise amplitude
	THETA = 0.5
	MU = COMPUTE_MEAN_FATIGUE(PREV_FLOOR)
	SIGMA =0.5
	
	FATIGUE = PREV_FATIGUE + THETA*(MU - PREV_FATIGUE) + SIGMA*RANDOMN(DATA_SEED)
	RETURN, FATIGUE
END

FUNCTION COMPUTE_MEAN_FATIGUE, PREV_FLOOR
	MU = 1
	IF (PREV_FLOOR LT 20 AND PREV_FLOOR GE 10) THEN BEGIN
		MU = 2
	ENDIF ELSE IF (PREV_FLOOR LT 30 AND PREV_FLOOR GE 20) THEN BEGIN
		MU = 3
	ENDIF ELSE IF (PREV_FLOOR LT 40 AND PREV_FLOOR GE 30) THEN BEGIN
		MU = 4
	ENDIF ELSE IF (PREV_FLOOR LT 50 AND PREV_FLOOR GE 40) THEN BEGIN
		MU = 5
	ENDIF

	RETURN, MU
END

;PRO BELL_FATIGUE
;; test function...
;RESULT = COMPUTE_MEAN_FATIGUE(9)

;END

