FUNCTION COMPUTE_FLOOR, DATA_SEED, PREV_FLOOR, FATIGUE
	; Fatigue impact floor progression: lower means lower percent change to go to prev floor
	FATIGUE_BIAS = FATIGUE / 10.0 ; Noramlized to 0-1
	; FOR MIGRATION: TO FORCE A FLOAT YOU HAVE TO AT LEAST SPECIFY ONE FLOAT NUMBER (10.0 FOR INSTANCE)
	RAND = RANDOMU(DATA_SEED)
	PRINT, FATIGUE_BIAS
	
	IF (RAND LE FATIGUE_BIAS) THEN BEGIN
	
		IF (PREV_FLOOR EQ 0) THEN BEGIN
			RETURN, PREV_FLOOR
		ENDIF

		RETURN, PREV_FLOOR-1
	
	ENDIF
	
	IF (PREV_FLOOR EQ 50) THEN BEGIN
		RETURN, PREV_FLOOR
	ENDIF
	
	RETURN, PREV_FLOOR+1
END

PRO CALC_FLOOR 
	DATA_SEED = LONG(SYSTIME(1))
	PREV_FLOOR = 5
	FATIGUE = 8
	RESULT = COMP_FLOOR(DATA_SEED, PREV_FLOOR, FATIGUE)
	PRINT, RESULT
END