FUNCTION CALC_XP_EARNT, DATA_SEED, CUR_FLOOR
	XP_MAX = 999
	
	XP = XP_MAX * ALOG(CUR_FLOOR + 1) / ALOG(51)
	
	; JUMP EXCEPTIONAL CASES +20% XP
	JUMP_CHANCE = 0.02
	RAND = RANDOMU(DATA_SEED)
	
	IF (RAND LT JUMP_CHANCE) THEN BEGIN
		XP = XP*1.2
	ENDIF
	
	RETURN, XP
END

FUNCTION CALC_NB_ENEMIES, CUR_FLOOR, PREV_ENEMIES

	MAX_ENEMIES = 1000
	FLOOR_ENEMIES =  PREV_ENEMIES + ALOG(CUR_FLOOR * 5)/4 ; Even when Bell comes back to precedent floor, enemies amount becomes higher, all floor get harder when re-visiting
	
	IF (FLOOR_ENEMIES GT MAX_ENEMIES) THEN BEGIN
		RETURN, MAX_ENEMIES
	ENDIF
	
	RETURN, FLOOR_ENEMIES

END

FUNCTION CALC_TIME_TAKEN, BASE_TIME, CUR_FLOOR, FATIGUE, ENEMIES

	TIME = BASE_TIME * ALOG(CUR_FLOOR + 1) * (1 + FATIGUE/10.0) * (ENEMIES/5.0)
	RETURN, TIME

END